 #-------------------------------------------------------------------------
  #
  # Makefile for storage/tracking
  #
  # IDENTIFICATION
  #   src/backend/storage/tracking/Makefile
  #
  #-------------------------------------------------------------------------

  subdir = src/backend/storage/tracking
  top_builddir = ../../../..
  include $(top_builddir)/src/Makefile.global

  OBJS = \
      atomic_tracking_stats.o \
      locking_tracking_stats.o

  include $(top_srcdir)/src/backend/common.mk